// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaSidT0R6NbgjTJcHTIyMtU3TxP3kVa3E',
    appId: '1:713421855431:web:91a8ff39be95dcc50a7ce2',
    messagingSenderId: '713421855431',
    projectId: 'instragram-clone-6ac50',
    authDomain: 'instragram-clone-6ac50.firebaseapp.com',
    storageBucket: 'instragram-clone-6ac50.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr38ri0fKNU4dICtoiKs3i5v6txLDIOpg',
    appId: '1:713421855431:android:6ae7b45325c015b50a7ce2',
    messagingSenderId: '713421855431',
    projectId: 'instragram-clone-6ac50',
    storageBucket: 'instragram-clone-6ac50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiMG4LK-MAzUPWdt3EZQ8pJGjJtNpDAPs',
    appId: '1:713421855431:ios:318628cc0d5d74940a7ce2',
    messagingSenderId: '713421855431',
    projectId: 'instragram-clone-6ac50',
    storageBucket: 'instragram-clone-6ac50.appspot.com',
    iosBundleId: 'com.example.instagramclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiMG4LK-MAzUPWdt3EZQ8pJGjJtNpDAPs',
    appId: '1:713421855431:ios:318628cc0d5d74940a7ce2',
    messagingSenderId: '713421855431',
    projectId: 'instragram-clone-6ac50',
    storageBucket: 'instragram-clone-6ac50.appspot.com',
    iosBundleId: 'com.example.instagramclone',
  );
}
